In [5]:
import cv2
import pandas as pd
import numpy as np
import urllib.request
import os
import requests

In [10]:


animals = ['Cat', 'Dog', 'Elephant', 'Parrot', 'Cow']
n= 0
arr= []
label = []

for i in animals:
    url = f"https://free-images-api.p.rapidapi.com/images/{i}"

    headers = {
        "X-RapidAPI-Key": "169656dc12mshc51db39aae904f7p1f9cadjsnc03266fb5929",
        "X-RapidAPI-Host": "free-images-api.p.rapidapi.com"}

    response = requests.get(url, headers=headers)
    data = pd.json_normalize(response.json(),record_path = ['results'] )
    path = os.getcwd()+f'\\{i}'
    os.makedirs(path, exist_ok=True)
    os.chdir(f'G:\Animal Task\\{i}')
    
    
    for j in data['image']:
        urllib.request.urlretrieve(j,f'G:\Animal Task\\{i}\\{i}{n}.jpg')
        n = n+1
    for k in os.listdir():
        path_new = os.getcwd()+f'\\{k}'
        image = cv2.imread(path_new)
        im = cv2.resize(image,(7,6))
        arr.append(im.flatten())
        label.append(i)
dd = pd.DataFrame(arr)
dd['label'] = label

In [11]:
dd

,0,1,2,3,4,5,6,7,8,9,...,117,118,119,120,121,122,123,124,125,label
0,4,116,182,1,43,107,14,134,200,3,...,44,70,57,38,60,56,36,53,42,Cat
1,108,136,77,115,147,82,122,155,89,125,...,65,73,91,70,106,142,74,106,141,Cat
2,83,178,227,86,182,228,88,185,229,89,...,209,215,222,73,175,223,70,168,216,Cat
3,97,97,96,103,104,100,109,108,104,110,...,52,59,62,138,152,161,184,192,199,Cat
4,195,198,202,178,187,197,79,105,129,140,...,113,131,148,156,163,171,193,195,203,Cat
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,152,153,157,110,121,135,56,66,73,26,...,57,73,85,32,44,54,50,60,68,Cow
96,3,3,15,29,25,36,122,131,118,192,...,123,138,154,123,135,147,139,148,157,Cow
97,190,181,167,208,204,193,228,227,217,230,...,1,117,76,37,98,81,42,181,144,Cow
98,202,140,92,206,147,98,211,150,100,212,...,35,96,88,46,68,68,14,37,29,Cow
99,149,114,81,152,120,81,157,126,93,158,...,196,183,168,200,189,175,217,219,223,Cow

In [13]:
dd.to_csv("Animal_Task_Assignment.csv")